
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Choose extends javax.swing.JFrame {

    /**
     * Creates new form Choose
     */
    public Choose(String name) 
    {
        initComponents(); 
        this.name=name;   
        user_name.setText("Hi "+name);
        jLabel2.setVisible(false);
        jButton1.setVisible(false);
        hostiptf.setVisible(false);
        setVisible(true);
    }
    String name,address,ip,port;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        join = new javax.swing.JButton();
        host = new javax.swing.JButton();
        user_name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        hostiptf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Compete Mode");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 70, 230, 60);

        join.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        join.setForeground(new java.awt.Color(51, 0, 240));
        join.setText("JOIN");
        join.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionPerformed(evt);
            }
        });
        jPanel1.add(join);
        join.setBounds(160, 180, 80, 30);

        host.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        host.setForeground(new java.awt.Color(51, 0, 240));
        host.setText("HOST");
        host.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostActionPerformed(evt);
            }
        });
        jPanel1.add(host);
        host.setBounds(390, 180, 80, 30);

        user_name.setBackground(new java.awt.Color(0, 255, 255));
        user_name.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        user_name.setForeground(new java.awt.Color(0, 204, 255));
        user_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(user_name);
        user_name.setBounds(190, 10, 230, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tick-512.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 250, 50, 30);

        hostiptf.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        hostiptf.setForeground(new java.awt.Color(153, 0, 153));
        jPanel1.add(hostiptf);
        hostiptf.setBounds(210, 250, 180, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(enter host ip)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 280, 130, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboard.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 612, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void joinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionPerformed
      jLabel2.setVisible(true);
      jButton1.setVisible(true);
      hostiptf.setVisible(true); 
    }//GEN-LAST:event_joinActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     address=hostiptf.getText();
     String val[]=address.split(":");
     ip=val[0];
     port=val[1];
     Client cts=new Client(name,ip,Integer.parseInt(port));
     cts.communicate();
     Thread th2=new Thread(new Runnable() {
         @Override
         public void run()
         {
         new Initialize("client",ip,name,null,cts);
         }
     });
     th2.start();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void hostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostActionPerformed
     Server ser=new Server(name); 
        Thread th=new Thread(new Runnable() {

         @Override
         public void run() {
             new Initialize("host","",name,ser,null); 
              }
     });
     th.start();
     Thread th1=new Thread(new Runnable() {

         @Override
         public void run() {
             ser.communicate();
              }
     });
     th1.start();
    }//GEN-LAST:event_hostActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton host;
    private javax.swing.JTextField hostiptf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton join;
    private javax.swing.JLabel user_name;
    // End of variables declaration//GEN-END:variables
}
