
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    String name;
    String headpath=new Provide_path().getHeadpath();
    public UserForm() {
        initComponents();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        int xw=(int)d.getWidth();
        int xh=(int)d.getHeight();
        int w=getWidth();
        int h=getHeight();
        setLocation((xw-w)/2,(xh-h)/2);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginFormPanel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        userPassword = new javax.swing.JLabel();
        userTextfield = new javax.swing.JTextField();
        userTextPassword = new javax.swing.JPasswordField();
        loginEnter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        loginWallpaper = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        regLabel = new javax.swing.JLabel();
        regPassword = new javax.swing.JLabel();
        regTextfield = new javax.swing.JTextField();
        regEnter = new javax.swing.JButton();
        regLabel2 = new javax.swing.JLabel();
        regTextPassword = new javax.swing.JPasswordField();
        regTextPassword2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        regWallpaper = new javax.swing.JLabel();
        regLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        LoginFormPanel.setLayout(null);

        jTabbedPane1.setForeground(new java.awt.Color(51, 0, 51));

        jPanel1.setLayout(null);

        userLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        userLabel.setText("Password");
        jPanel1.add(userLabel);
        userLabel.setBounds(90, 170, 70, 30);

        userPassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        userPassword.setText("UserName");
        jPanel1.add(userPassword);
        userPassword.setBounds(90, 110, 70, 30);

        userTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTextfieldActionPerformed(evt);
            }
        });
        jPanel1.add(userTextfield);
        userTextfield.setBounds(210, 110, 180, 30);
        jPanel1.add(userTextPassword);
        userTextPassword.setBounds(210, 170, 180, 30);

        loginEnter.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        loginEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/login.png"))); // NOI18N
        loginEnter.setText("Enter");
        loginEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEnterActionPerformed(evt);
            }
        });
        jPanel1.add(loginEnter);
        loginEnter.setBounds(180, 260, 110, 30);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Type Racer");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(170, 10, 160, 30);

        loginWallpaper.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        loginWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboard.jpg"))); // NOI18N
        jPanel1.add(loginWallpaper);
        loginWallpaper.setBounds(0, 0, 490, 420);

        jTabbedPane1.addTab("Login", jPanel1);

        jPanel2.setLayout(null);

        regLabel.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        regLabel.setText("Password");
        jPanel2.add(regLabel);
        regLabel.setBounds(90, 170, 70, 30);

        regPassword.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        regPassword.setText("UserName");
        jPanel2.add(regPassword);
        regPassword.setBounds(90, 110, 70, 30);
        jPanel2.add(regTextfield);
        regTextfield.setBounds(230, 110, 180, 30);

        regEnter.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        regEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/new.png"))); // NOI18N
        regEnter.setText("Enter");
        regEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regEnterActionPerformed(evt);
            }
        });
        jPanel2.add(regEnter);
        regEnter.setBounds(180, 300, 110, 30);

        regLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        regLabel2.setText("Re-enter Password");
        jPanel2.add(regLabel2);
        regLabel2.setBounds(70, 230, 130, 30);
        jPanel2.add(regTextPassword);
        regTextPassword.setBounds(230, 230, 180, 30);
        jPanel2.add(regTextPassword2);
        regTextPassword2.setBounds(230, 170, 180, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Type Racer");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 10, 160, 30);

        regWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyboard.jpg"))); // NOI18N
        jPanel2.add(regWallpaper);
        regWallpaper.setBounds(0, 0, 490, 420);

        regLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        regLabel1.setText("Password");
        jPanel2.add(regLabel1);
        regLabel1.setBounds(90, 170, 70, 30);

        jTabbedPane1.addTab("Register", jPanel2);

        LoginFormPanel.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 500, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoginFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regEnterActionPerformed
        // TODO add your handling code here:
        String name=regTextfield.getText();
        
        String pass1=regTextPassword.getText();
        String pass2=regTextPassword2.getText();
        if(!pass1.equals(pass2))
        {
            JOptionPane.showMessageDialog(null,"Password doesn't match!");
        }
        else
        {
        File f=new File(headpath+"\\user\\new_users");
        BufferedWriter br=null;
        FileWriter fr=null;
        try {
            fr=new FileWriter(f.getAbsoluteFile(),true);
            br=new BufferedWriter(fr);
            String s=name+":"+pass1+"\n";
            br.write(s);
            br.close();
            fr.close();
            new Welcome();
            setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(Arena.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_regEnterActionPerformed

    private void userTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTextfieldActionPerformed

    private void loginEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEnterActionPerformed
        // TODO add your handling code here:
        String name=userTextfield.getText();
        String pass=userTextPassword.getText();
        File f=new File(headpath+"\\user\\new_users");
        BufferedReader in;
        int flag=0;
        try {
            in = new BufferedReader(new FileReader(f.getAbsolutePath()));
            String s;
            while((s = in.readLine()) != null){
            String[] var = s.split(":");
            if(var[0].equals(name)&& var[1].equals(pass))
            {
                flag=1;
                new loggedInFrame(name);
                setVisible(false);
                break;
            }
            }
            if(flag==0)
            {
                JOptionPane.showMessageDialog(null,"User not Recognised!!");
            }
            in.close();
         }
        catch (FileNotFoundException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginFormPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loginEnter;
    private javax.swing.JLabel loginWallpaper;
    private javax.swing.JButton regEnter;
    private javax.swing.JLabel regLabel;
    private javax.swing.JLabel regLabel1;
    private javax.swing.JLabel regLabel2;
    private javax.swing.JLabel regPassword;
    private javax.swing.JPasswordField regTextPassword;
    private javax.swing.JPasswordField regTextPassword2;
    private javax.swing.JTextField regTextfield;
    private javax.swing.JLabel regWallpaper;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel userPassword;
    private javax.swing.JPasswordField userTextPassword;
    private javax.swing.JTextField userTextfield;
    // End of variables declaration//GEN-END:variables
}
